Repository microsoft/appcenter-cli, pull requests merged in 2020-06, with the labels that each got.

#903 Fix functional tests: require pester 4.x
  test/functional/Invoke-FunctionalTests.ps1
Labels: Maintenance

#910 Extract a filename from path
  src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader-types.ts
  src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader.ts
Labels: target-not-master

#920 Fix all the unit tests
  package.json
  src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader.ts
  test/commands/distribute/release/mockWorker.js
  test/commands/distribute/release/release-test.ts
Labels: target-not-master

#923 Fix functional tests
  src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader.ts
  test/functional/commands/distribute/Release.Tests.ps1
  test/functional/dummyapk.apk
Labels: target-not-master

#905 Add build version and build number to request
  src/commands/distribute/release.ts
Labels: target-not-master

#925 Address feature feedbacks
  package-lock.json
  package.json
  src/commands/distribute/lib/mc-fus-uploader/mc-fus-api.ts
  src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader-types.ts
  src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader.ts
  src/commands/distribute/release.ts
  src/util/portal/portal-helper.ts
Labels: target-not-master

#927 Fix getting the proper endpoint
  src/commands/distribute/release.ts
Labels: target-not-master

#928 Fix integration tests
  test/functional/commands/distribute/Release.Tests.ps1
  test/functional/dummyapk.apk
Labels: target-not-master

#929 Address fus-library feedback
  src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader-types.ts
  src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader.ts
  src/commands/distribute/lib/mc-fus-uploader/readme.md
  src/commands/distribute/release.ts
  test/commands/distribute/lib/mc-fus-uploader-test.ts
Labels: target-not-master

#909 Use App Center File Uploader Service for release uploading
  package-lock.json
  package.json
  src/commands/distribute/lib/mc-fus-uploader/mc-fus-api.ts
  src/commands/distribute/lib/mc-fus-uploader/mc-fus-mime-types.ts
  src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader-types.ts
  src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader.ts
  src/commands/distribute/lib/mc-fus-uploader/readme.md
  src/commands/distribute/release.ts
  test/commands/distribute/lib/mc-fus-uploader-test.ts
  test/commands/distribute/release/release-test.ts
  test/functional/commands/distribute/Release.Tests.ps1
Labels: Distribute

#848 Add `orgs apps create` command.
  src/commands/apps/lib/format-app.ts
  src/commands/orgs/apps/create.ts
  test/commands/orgs/apps/create-test.ts
Labels: feature-request

#930 Add dependabot.yml to enable dependabot beta
  .github/dependabot.yml
Labels: Maintenance

#931 CI: Add steps to verify test result files exist
  azure-pipelines.yml
  package.json
Labels: Maintenance
